server:
  port: 10001
spring:
  application:
    name: itoken-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    instance-id: test-10001
    ip-address: true
